### PR TITLE
Make README.md honest

### PR DESCRIPTION
**Pull request by spendergrsec**
Because a little honesty is needed.

### CODE REVIEW

**Comment by paragonie-scott** [comment]
:+1:

**Comment by JonathonReinhart** [comment]
:+1:

**Comment by gannimo** [comment]
The demo shows the interpreter in a simple setting. To run the interpreter in the wild the attacker first needs to modify the printf internal state to enable %n and disable the write check for strings. There's a great phrack article about this.

**Comment by spendergrsec** [comment]
PS: The 2nd check was fixed over 3 years ago:
https://sourceware.org/ml/libc-alpha/2012-03/msg00061.html

**Pull request closed without merging**
